name: Deploy TqsftNatInstance

permissions:
 id-token: write # Required for GitHub to be able to create a token for you to authenticate with AWS
 contents: read  # Permits your action to read this repo.

on:
 push:
   branches:
     - main

jobs:
 deploy_nat_instance_stack:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout this repo
       uses: actions/checkout@v3

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
         aws-region: ${{ vars.AWS_TARGET_REGION }}
         role-session-name: "DeployNatInstance"

     - name: Deploy TqsftNatInstanceStack (via CDK)
       uses: youyo/aws-cdk-github-actions@v2
       with:
         cdk_subcommand: 'deploy'
         cdk_stack: 'TqsftVpcStack'
         cdk_args: '--parameters KeyPairName=${{ vars.KEY_PAIR_NAME }} --require-approval never' 
         actions_comment: false